# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatServerMessages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChatServerMessages.proto',
  package='avxer.chat',
  serialized_pb='\n\x18\x43hatServerMessages.proto\x12\navxer.chat\"<\n\x10UserLoginRequest\x12\x12\n\nlogin_name\x18\x01 \x02(\t\x12\x14\n\x0clogin_passwd\x18\x02 \x02(\t\"\'\n\x11UserLoginResponse\x12\x12\n\nerror_code\x18\x01 \x02(\x05\"\x13\n\x11UserLogoutRequest\"\x13\n\x11\x41\x64minLoginRequest\"\x14\n\x12\x41\x64minLogoutRequest\"\x0f\n\rUserEnterNtfy\"\x0f\n\rUserLeaveNtfy\"\x11\n\x0fRoomChatMessage\"\x13\n\x11SystemChatMessage\"\x14\n\x12PrivateChatMessage\"\x0f\n\rKeepAliveNtfy\"\r\n\x0bPingRequestB\x02H\x03')




_USERLOGINREQUEST = _descriptor.Descriptor(
  name='UserLoginRequest',
  full_name='avxer.chat.UserLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login_name', full_name='avxer.chat.UserLoginRequest.login_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='login_passwd', full_name='avxer.chat.UserLoginRequest.login_passwd', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=100,
)


_USERLOGINRESPONSE = _descriptor.Descriptor(
  name='UserLoginResponse',
  full_name='avxer.chat.UserLoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='avxer.chat.UserLoginResponse.error_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=141,
)


_USERLOGOUTREQUEST = _descriptor.Descriptor(
  name='UserLogoutRequest',
  full_name='avxer.chat.UserLogoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=143,
  serialized_end=162,
)


_ADMINLOGINREQUEST = _descriptor.Descriptor(
  name='AdminLoginRequest',
  full_name='avxer.chat.AdminLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=183,
)


_ADMINLOGOUTREQUEST = _descriptor.Descriptor(
  name='AdminLogoutRequest',
  full_name='avxer.chat.AdminLogoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=185,
  serialized_end=205,
)


_USERENTERNTFY = _descriptor.Descriptor(
  name='UserEnterNtfy',
  full_name='avxer.chat.UserEnterNtfy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=207,
  serialized_end=222,
)


_USERLEAVENTFY = _descriptor.Descriptor(
  name='UserLeaveNtfy',
  full_name='avxer.chat.UserLeaveNtfy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=224,
  serialized_end=239,
)


_ROOMCHATMESSAGE = _descriptor.Descriptor(
  name='RoomChatMessage',
  full_name='avxer.chat.RoomChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=258,
)


_SYSTEMCHATMESSAGE = _descriptor.Descriptor(
  name='SystemChatMessage',
  full_name='avxer.chat.SystemChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=260,
  serialized_end=279,
)


_PRIVATECHATMESSAGE = _descriptor.Descriptor(
  name='PrivateChatMessage',
  full_name='avxer.chat.PrivateChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=281,
  serialized_end=301,
)


_KEEPALIVENTFY = _descriptor.Descriptor(
  name='KeepAliveNtfy',
  full_name='avxer.chat.KeepAliveNtfy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=303,
  serialized_end=318,
)


_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='avxer.chat.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=320,
  serialized_end=333,
)

DESCRIPTOR.message_types_by_name['UserLoginRequest'] = _USERLOGINREQUEST
DESCRIPTOR.message_types_by_name['UserLoginResponse'] = _USERLOGINRESPONSE
DESCRIPTOR.message_types_by_name['UserLogoutRequest'] = _USERLOGOUTREQUEST
DESCRIPTOR.message_types_by_name['AdminLoginRequest'] = _ADMINLOGINREQUEST
DESCRIPTOR.message_types_by_name['AdminLogoutRequest'] = _ADMINLOGOUTREQUEST
DESCRIPTOR.message_types_by_name['UserEnterNtfy'] = _USERENTERNTFY
DESCRIPTOR.message_types_by_name['UserLeaveNtfy'] = _USERLEAVENTFY
DESCRIPTOR.message_types_by_name['RoomChatMessage'] = _ROOMCHATMESSAGE
DESCRIPTOR.message_types_by_name['SystemChatMessage'] = _SYSTEMCHATMESSAGE
DESCRIPTOR.message_types_by_name['PrivateChatMessage'] = _PRIVATECHATMESSAGE
DESCRIPTOR.message_types_by_name['KeepAliveNtfy'] = _KEEPALIVENTFY
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST

class UserLoginRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLOGINREQUEST

  # @@protoc_insertion_point(class_scope:avxer.chat.UserLoginRequest)

class UserLoginResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLOGINRESPONSE

  # @@protoc_insertion_point(class_scope:avxer.chat.UserLoginResponse)

class UserLogoutRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLOGOUTREQUEST

  # @@protoc_insertion_point(class_scope:avxer.chat.UserLogoutRequest)

class AdminLoginRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADMINLOGINREQUEST

  # @@protoc_insertion_point(class_scope:avxer.chat.AdminLoginRequest)

class AdminLogoutRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADMINLOGOUTREQUEST

  # @@protoc_insertion_point(class_scope:avxer.chat.AdminLogoutRequest)

class UserEnterNtfy(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERENTERNTFY

  # @@protoc_insertion_point(class_scope:avxer.chat.UserEnterNtfy)

class UserLeaveNtfy(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLEAVENTFY

  # @@protoc_insertion_point(class_scope:avxer.chat.UserLeaveNtfy)

class RoomChatMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROOMCHATMESSAGE

  # @@protoc_insertion_point(class_scope:avxer.chat.RoomChatMessage)

class SystemChatMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYSTEMCHATMESSAGE

  # @@protoc_insertion_point(class_scope:avxer.chat.SystemChatMessage)

class PrivateChatMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRIVATECHATMESSAGE

  # @@protoc_insertion_point(class_scope:avxer.chat.PrivateChatMessage)

class KeepAliveNtfy(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEEPALIVENTFY

  # @@protoc_insertion_point(class_scope:avxer.chat.KeepAliveNtfy)

class PingRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGREQUEST

  # @@protoc_insertion_point(class_scope:avxer.chat.PingRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
